#Common Configuration Parameters
gem_left_foot_wrench_topic: "/left_ankle_ft"  #left foot FT
gem_right_foot_wrench_topic: "/right_ankle_ft" #right foot FT
gem_freq: 100    #min freq of all topics
gem_lfoot_frame: "left_sole_link"   #left foot frame 
gem_rfoot_frame: "right_sole_link"   #right foot frame 
gem_mass: 5.14
gem_no_diff: True
gem_gravity: 9.81
gem_direct_gt: True
gem_cf: True
gem_cf_a: 0.99
#Unsupervisead Gait Phase Learning Parameters
useUL: True  #Use Unsupervised Learning (Dimensionality Reduction + Clustering) for  Gait Phase Estimation
#Only if use_UL is True
gem_imu_topic: "/torso_imu" # base_link (body) IMU
gem_com_topic: "/gem/rel_CoM/position"  #relative to base_link (body) CoM - computed with kinematics
gem_plot_results: True #plot the results only works when Dimensionality Reduction is performed
gem_dim: 2
gem_gt_comparison: True  #compare to ground-truth, to do so user must supply true friction coefficient mu and ground reaction forces and torques.
gem_save: False  #Save the Training Results to load in real-time
gem_dim_reduction: "autoencoders"
gem_clustering: "gmm" #gmm or kmeans supported at the current time
gem_train_path: "../GEM2_talos_training" #path to training data relative to src e.g. "../gem/src/gem_train_path", data must have same(or approx. same) sampling rate e.g. gem_freq.
gem_lfoot_torque_bias: [0, 0, 0] #left foot FT bias  
gem_lfoot_force_bias: [0, 0, 0] 
gem_rfoot_torque_bias: [0, 0, 0] #right foot FT bias 
gem_rfoot_force_bias: [0, 0, 0]