#Common Configuration Parameters
gem_left_foot_wrench_topic: "/gem/LLeg/force_torque_states"  #left foot FT
gem_right_foot_wrench_topic: "/gem/RLeg/force_torque_states" #right foot FT
gem_freq: 100    #min freq of all topics
gem_lfoot_frame: "l_ankle"   #left foot frame 
gem_rfoot_frame: "r_ankle"   #right foot frame 
gem_mass: 5.14
gem_gravity: 9.81
#Unsupervisead Gait Phase Learning Parameters
useUL: False  #Use Unsupervised Learning (Dimensionality Reduction + Clustering) for  Gait Phase Estimation
#Only if use_UL is True
gem_imu_topic: "/gem/rel_base_imu" # base_link (body) IMU
gem_com_topic: "/gem/rel_CoM/pose"  #relative to base_link (body) CoM - computed with kinematics
gem_plot_results: True #plot the results only works when Dimensionality Reduction is performed
gem_dim: 2
gem_gt_comparison: False  #compare to ground-truth, to do so user must supply true friction coefficient mu and ground reaction forces and torques.
gem_save: False  #Save the Training Results to load in real-time
#gem_dim_reduction: "supervisedClassifier" 
#gem_dim_reduction: "supervisedVariationalAutoencoders" 
#gem_dim_reduction: "pca"
gem_dim_reduction: "supervisedAutoencoders"
useLabels: True

gem_clustering: "gmm" #gmm or kmeans supported at the current time
#gem_train_path: "/home/master/gem_ws/src/gem/src/GEM2_test_nao" #path to training data, data must have same(or approx. same) sampling rate e.g. gem_freq.
gem_train_path: "../GEM2_nao_training" #path to training data relative to src e.g. "../gem/src/gem_train_path", data must have same(or approx. same) sampling rate e.g. gem_freq.
gem_validation_path: "../GEM2_nao_validation/NAO5" #path to training data relative to src e.g. "../gem/src/gem_train_path", data must have same(or approx. same) sampling rate e.g. gem_freq.
gem_validation: True
gem2: True
gem_lfoot_torque_bias: [0, 0, 0] #left foot FT bias  
gem_lfoot_force_bias: [0, 0, 0] 
gem_rfoot_torque_bias: [0, 0, 0] #right foot FT bias 
gem_rfoot_force_bias: [0, 0, 0]
